### ISSUE TITLE
[OneToolchain]  Introduce OneToolchain 

### ISSUE THREAD

**Issue by YeonJeongLee00** [Samsung/ONE-vscode#1271]
### What
Let’s introduce **OneToolchain**.

### Why

Currently, the toolchain cannot be installed unless Backend extensions are installed. `OneToolchain` will be installed without a Backend extension to support the use of `run onecc` without a backend.

#### Scenario Video
[Scenario Video](https://user-images.githubusercontent.com/67946956/190300606-050fd78c-0abe-4eaf-83a1-1fb013ed1ca7.webm)

#### Step by step
1. click the `+` button to select a backend (in this scenario it means ONEToolchain; implemetation of Backend interface)

![1](https://user-images.githubusercontent.com/67946956/190300135-bc2cb46a-c12f-41fc-8dfc-f1cc19373b2f.PNG)

2. Select Toolchain type (We’re going to support only the “latest” type for now)  

![2](https://user-images.githubusercontent.com/67946956/190300182-f8ed634c-2223-4220-a88d-561b8d6300f4.PNG)

3. Select Toolchain version (latest version)

![3](https://user-images.githubusercontent.com/67946956/190300199-1e082276-e910-40fa-ae67-d619e8a6f616.PNG)

### TODO

- [x] #1289 
    - [x]  name() (maybe,  OneToolchain)
    - [x] `ToolchainCompiler` (temporary name) implementation based on Compiler interface
        - [x]  getToolchains()
        - [x]  getInstalledToolchains()
        - [x]  prerequsitedsForGetToolchains()
            - [x]  shell script  (for preparing to use toolchains)
                - [x]  add ppa address to /etc/apt/source.list
                - [x]  install onecc-docker(temporary name)
    - [x] modify DebianToolchain (to run onecc-docker)
    - [x] Add OneToolchain Guide in Tutorial.md
    - [x] #1285
    

    onecc-docker : [https://github.com/Samsung/ONE/issues/9697#issuecomment-1244794823](https://github.com/Samsung/ONE/issues/9697#issuecomment-1244794823)
   
    related issue : #1265 

/cc **[@Samsung/ootpg](https://github.com/orgs/Samsung/teams/ootpg)**

**Comment by jyoungyun** [comment]
I think the toolchain name should be `ONE` without `Toolchain`. 

I agree to start by installing the `onecc-docker` debian package as the first step. Let's think about how to use the docker after `onecc-docker` is well applied. :)

**Comment by lettersto** [comment]
Oh, I havs two questions!

> I think the toolchain name should be `ONE` without `Toolchain`.

Q) I thought ONE is a directory. Do you mean, the file structure should be like `/src/Backend/ONE.ts` or `/src/Backend/ONE/ONE.ts`?


> I agree to start by installing the `onecc-docker` debian package as the first step. Let's think about how to use the docker after `onecc-docker` is well applied. :)

Q) Is this about `prerequsitedsForGetToolchains()` in Compiler interface?

**Comment by jyoungyun** [comment]
> Q) I thought ONE is a directory. Do you mean, the file structure should be like `/src/Backend/ONE.ts` or `/src/Backend/ONE/ONE.ts`?

I mean that the toolchain name shown in the quick input of ONE-vscode should be `ONE`. Now, it is seen as `ONEToolchain` in the first step image.


> Q) Is this about `prerequsitedsForGetToolchains()` in Compiler interface? 

Yes, that is correct. But not now. After applying the first design, let's think about the next step. :)

**Comment by lettersto** [comment]
> I mean that the toolchain name shown in the quick input of ONE-vscode should be `ONE`. Now, it is seen as `ONEToolchain` in the first step image.

Oh, thank you! That's a good point. We will change the name :)

**Comment by llFreetimell** [comment]
If this task is done, how about closing this issue? :)
