### ISSUE TITLE
[CircleEditor] Refactoring structure and codes

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#1455]
### What?

Let's refactor overall structure and source codes for `CircleEditor`.

### Why?

- To improve static analysis score
- To improve readability and maintainability
  - Remove source codes which are not related with editing circle file
  - Rename variable and functions
- To fix bugs

#### Draft

- #1454

---

#### TODO Items

- [ ] Minimize duplicated source codes
  - [ ] Reposition external source codes
  - [ ] Remove not modified source codes from our own codes
- [ ] Remove source codes which are not related with editing circle file
- [ ] Rename variable and functions which have unclear names
- [ ] Fix bugs
  - [ ] Edit custom attribute --> Ctrl+z --> arrows are dismissed
  - [ ] BCQ(maybe some other operations too) attribute types are null

**Comment by llFreetimell** [comment]
#### Feature Requests

- When duplicated keys for custom option are given, alert
