### ISSUE TITLE
[Circle-OpSelector] Introduction to GUI tool for Circle-OpSelector

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE-vscode#147]
_This issue was originally posted [here](https://github.com/Samsung/ONE/issues/7760), but it was considered [more appropriate](https://github.com/Samsung/ONE/issues/7760#issuecomment-927516937) to be in the `ONE-vscode` Issues. The original issue is closed._

Hi! This is team Cosmos developing [`Circle-OpSelector`](https://github.com/Samsung/ONE/issues/7596)

This Issue introduces the GUI tool for `Circle-OpSelector`.

## why

`Circle-OpSelector` is a tool to slice a `circle` model for convenience in debugging. An user can slice a `circle` model by typing code in **CLI**.

We thought that if this could be done by **GUI**, that is, if the slicing can be done in a graphical environment, the convenience would increase. That is why we are trying to develop a GUI tool for `Circle-OpSelector`.

## goal

The main purpose of this tool is to enable `Circle-OpSelector` features using **mouse cursor**. Slicing the graph should be done by just a couple of mouse clicks.

The picture below is the blueprint of the usage of the tool. Visualization is done using `inception_v3` file and [Netron](https://github.com/lutzroeder/netron) .

![image-20210925003521103](https://user-images.githubusercontent.com/46149751/134800608-f1c8678d-fc40-482d-8ac9-8fd07f0d203b.png)

By selecting several nodes with the cursor, the user would be able to create a subgraph(a new `circle` file).

## how

I'm using [Vue](https://vuejs.org/) to create this application. `Vue` is a JS framework for creating web pages, web applications, etc. The only reason why I chose this framework is because I am used to using `Vue`,  so I can't guarantee that this is the best option.

### Todo List

- [ ] create `flatbuffers.js`
- [ ] create a `Vue` project
- [ ] make the application read `Circle` file input(using `flatbuffers.js`)
- [ ] visualize the graph
- [ ] enable selecting nodes by `click` event
- [ ] create a new subgraph using the selected nodes. 

For creating a new subgraph, there are 2 options I'm considering. 

1. Activate the developed `Circle-OpSelector` via the application.
2. Develop the `Circle-OpSelector` in `Javascript`.  

Currently I'm considering the first option and looking for a way to enable it.

*ps. I wanted to make sure I know all the codes in the visualization app, so I know where to apply the `Circle-OpSelector`code. This is the reason why I'm developing this tool from scratch and not using the codes in [Netron](https://github.com/lutzroeder/netron).*

**Comment by CODe1995** [comment]
This feature will be implemented in addition to the feature we visualized(#66).

**Comment by kevin622** [comment]
@CODe1995 
Below is the blueprint of the code I'm trying to add to the visualization tool.
Tutorial for building compiler can be found [here](https://github.com/Samsung/ONE/blob/master/docs/howto/how-to-build-compiler.md).

```js
// module to enable a node app to execute commands in shell
import { exec } from 'child_process'

// path to the circle-opselector(building Compiler is required)
const circleOpSelector = "ONE/build/compiler/circle-opselector/circle-opselector"

// selected via click event in the app
const selectedNodes = [1, 2]

// path to the input circle file
const inputCircle = "./input.circle"

// path where the output circle file would be created
const outputCircle = "./output.circle"

// the circle-opselector command
const command = `${circleOpSelector} --by_id "${selectedNodes}"  ${inputCircle} ${outputCircle}`

// execute the command
exec(command, function (error, stdout, stderr) {
    // print the result in console(the command is already executed)
    console.log(stdout);
    console.log(stderr);
    if (error !== null) {
        console.log(`exec error: ${error}`);
    }
})
```

**Comment by kevin622** [comment]
# Select by Dragging
![select_box](https://user-images.githubusercontent.com/46149751/135765835-bc364a0d-b9d5-4dc9-bd29-96850a0602d6.gif)

@glistening pointed out that selecting nodes should be done via dragging(click and move), for better UX.
In order to make the nodes be selected via dragging, I wrote some codes to enable this feature. 

The basic logic of this is to make a `html` object(a rectangle) while dragging, and selecting the nodes(pushing the selected nodes in a array) that are included in the rectangle.

Below are the codes.

<details>
<summary>index.html</summary>

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./index.css">
</head>
<body>
    <div>
        <button onclick="deselectAllNodes();">
            deselect all nodes
        </button>
    </div>
    <div class="canvas">
        <div class="node">
            node
        </div>
    </div>
    <script src="./select_test.js"></script>
    <script>
        drawSelectBox(document.getElementsByClassName("canvas")[0])
    </script>
</body>
</html>
```

</details>

<details>
<summary>index.css</summary>

```css
/* index.css */
.canvas {
    height: 1000px;
}

.select_box {
    border: 1px solid blue;
    position: absolute;
    background-color: blue;
    opacity: 50%;
}

.node {
    position: absolute;
    top: 95px;
    left: 96px;
    width: 77px;
    height: 88px;
    background-color: grey;
}

.selected_node {
    border: 3px solid black;
}
```

</details>

<details>
<summary>select_test.js</summary>

```javascript
// select_test.js
let selectedNodes = []
function drawSelectBox(canvas) {
    let mouse = {
        x: 0,
        y: 0,
        startX: 0,
        startY: 0
    };
    let element = null;

    canvas.onmousedown = function (e) {
        mouse.startX = mouse.x;
        mouse.startY = mouse.y;
        element = document.createElement('div');
        element.className = 'select_box'
        element.style.left = mouse.x + 'px';
        element.style.top = mouse.y + 'px';
        canvas.appendChild(element)
        canvas.style.cursor = "crosshair";
    }

    canvas.onmousemove = function (e) {
        mouse.x = e.clientX + document.body.scrollLeft;
        mouse.y = e.clientY + document.body.scrollTop;
        if (element !== null) {
            element.style.width = Math.abs(mouse.x - mouse.startX) + 'px';
            element.style.height = Math.abs(mouse.y - mouse.startY) + 'px';
            element.style.left = (mouse.x - mouse.startX < 0) ? mouse.x + 'px' : mouse.startX + 'px';
            element.style.top = (mouse.y - mouse.startY < 0) ? mouse.y + 'px' : mouse.startY + 'px';
        }
    }

    canvas.onmouseup = function (e) {
        const htmlCollection = document.getElementsByClassName('node')
        const nodes = Array.from(htmlCollection)
        const top = getMinVal(mouse.startY, mouse.y)
        const bottom = getMaxVal(mouse.startY, mouse.y)
        const left = getMinVal(mouse.startX, mouse.x)
        const right = getMaxVal(mouse.startX, mouse.x)

        nodes.forEach((node) => {
            const x = node.offsetLeft
            const y = node.offsetTop
            const w = node.offsetWidth
            const h = node.offsetHeight
            if (x >= left && y >= top && (x + w) <= right && (h + y) <= bottom) {
                selectedNodes.push(node)
                node.classList.add('selected_node')
            }
        })
        canvas.removeChild(element)
        element = null;
        canvas.style.cursor = "default";
    }
}

function getMaxVal(a, b) {
    if (a >= b) {
        return a
    } else {
        return b
    }
}

function getMinVal(a, b) {
    if (a <= b) {
        return a
    } else {
        return b
    }
}

function deselectAllNodes () {
    selectedNodes.forEach((node) => {
        node.classList.remove('selected_node')
    })
    selectedNodes = []
}
```

</details>

**Comment by glistening** [comment]
@kevin622 Good. I think it is much better just providing selection of a node. At first, I thought there may be a standard  for handling selection. When I searched, I've found "selection API" like https://developer.mozilla.org/en-US/docs/Web/API/Selection. But it says it is experimental and seems to handle text selection only. Anyway, at a glance, your code seems okay.

**Comment by kevin622** [comment]
I made sure that the logic above works on multiple nodes as well.

![node_select_multi](https://user-images.githubusercontent.com/46149751/135983004-76974abb-c2bf-40d1-b6a4-25ffe442fa48.gif)

There are some minor changes in the codes.

<details>
<summary>index.html</summary>

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./index.css">
</head>
<body>
    <div>
        <button onclick="deselectAllNodes();">
            deselect all nodes
        </button>
    </div>
    <div class="canvas">
        <div class="node node1">
            node
        </div>
        <div class="node node2">
            node
        </div>
        <div class="node node3">
            node
        </div>
        <div class="node node4">
            node
        </div>
    </div>
    <script src="./select_test.js"></script>
    <script>
        drawSelectBox(document.getElementsByClassName("canvas")[0])
    </script>
</body>
</html>
```

</details>

<details>
<summary>index.css</summary>

```css
/* index.css */
.canvas {
    height: 1000px;
}

.select_box {
    border: 1px solid blue;
    position: absolute;
    background-color: blue;
    opacity: 50%;
}

.node {
    position: absolute;
    background-color: grey;
}

.node1 {
    top: 95px;
    left: 96px;
    width: 77px;
    height: 88px;
}

.node2 {
    top: 200px;
    left: 96px;
    width: 77px;
    height: 88px;
}

.node3 {
    top: 150px;
    left: 200px;
    width: 77px;
    height: 88px;
}

.node4 {
    top: 400px;
    left: 100px;
    width: 200px;
    height: 200px;
}

.selected_node {
    border: 3px solid black;
}
```

</details>

<details>
<summary>select_test.js</summary>

```javascript
// select_test.js
let selectedNodes = []
function drawSelectBox(canvas) {
    let mouse = {
        x: 0,
        y: 0,
        startX: 0,
        startY: 0
    };
    let element = null;

    canvas.onmousedown = function (e) {
        mouse.startX = mouse.x;
        mouse.startY = mouse.y;
        element = document.createElement('div');
        element.className = 'select_box'
        element.style.left = mouse.x + 'px';
        element.style.top = mouse.y + 'px';
        canvas.appendChild(element)
        canvas.style.cursor = "crosshair";
    }

    canvas.onmousemove = function (e) {
        mouse.x = e.clientX + window.scrollX;
        mouse.y = e.clientY + window.scrollY;
        if (element !== null) {
            element.style.width = Math.abs(mouse.x - mouse.startX) + 'px';
            element.style.height = Math.abs(mouse.y - mouse.startY) + 'px';
            element.style.left = (mouse.x - mouse.startX < 0) ? mouse.x + 'px' : mouse.startX + 'px';
            element.style.top = (mouse.y - mouse.startY < 0) ? mouse.y + 'px' : mouse.startY + 'px';
        }
    }

    canvas.onmouseup = function (e) {
        const htmlCollection = document.getElementsByClassName('node')
        const nodes = Array.from(htmlCollection)
        const top = getMinVal(mouse.startY, mouse.y)
        const bottom = getMaxVal(mouse.startY, mouse.y)
        const left = getMinVal(mouse.startX, mouse.x)
        const right = getMaxVal(mouse.startX, mouse.x)

        nodes.forEach((node) => {
            const x = node.offsetLeft
            const y = node.offsetTop
            const w = node.offsetWidth
            const h = node.offsetHeight
            if (x >= left && y >= top && (x + w) <= right && (h + y) <= bottom) {
                if(!selectedNodes.includes(node)) {
                    selectedNodes.push(node)
                    node.classList.add('selected_node')
                }
            }
        })
        canvas.removeChild(element)
        element = null;
        canvas.style.cursor = "default";
    }
}

function getMaxVal(a, b) {
    if (a >= b) {
        return a
    } else {
        return b
    }
}

function getMinVal(a, b) {
    if (a <= b) {
        return a
    } else {
        return b
    }
}

function deselectAllNodes () {
    selectedNodes.forEach((node) => {
        node.classList.remove('selected_node')
    })
    selectedNodes = []
}
```

</details>

**Comment by glistening** [comment]
@kevin622

1) Is it possible to run arbitrary command using `exec` in VSCode Extension? I guess it is permitted for only privileged executables. I don't know much about `VSCode` extension, but I believe that there are some limitation for security.

2) You are going to use `circle_opselector` CLI (native executables), and `circle_opselector` only works on Linux. Thus, at first stage, it will work on Linux only. Is it right?

**Comment by kevin622** [comment]
> @kevin622
> 
> 1. Is it possible to run arbitrary command using `exec` in VSCode Extension? I guess it is permitted for only privileged executables. I don't know much about `VSCode` extension, but I believe that there are some limitation for security.

I'll check this ASAP.

> 2. You are going to use `circle_opselector` CLI (native executables), and `circle_opselector` only works on Linux. Thus, at first stage, it will work on Linux only. Is it right?

This is true. It would only work if `circle-opselector` is executable.

**Comment by seanshpark** [comment]
Closing as not active. Free free to reopen if needed.
