### ISSUE TITLE
Support model related functions

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#1562]
## What

Let's support model related functions such as inference, profiling and getting model information.

## Todo

- [x] Expand Backend Class
- [x] Introduce stdout result variable in JobRunner
- [x] Implement inference function
- [x] Implement profiling function
- [x] Implement function to get model information

Draft: #1552

**Comment by jyoungyun** [comment]
Done!
