### ISSUE TITLE
[CI] Enable License Checker

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#285]
### What?

If we use [`license-checker`](https://www.npmjs.com/package/license-checker) in `npm`, we can check the license of each packages.
With this tool, let's enable license checker in Github Action and make it easy to check each PR about license :D

### Why?

Some packages may have unacceptable license for ONE.
However, when PRs will be created a lot, it's really hard to verify each PR manually and there may be some mistakes.
To reduce such risk and labor, automatic license checker would be good solution!

### How?

I am planning to make a process as following flow!

![diagrams](https://user-images.githubusercontent.com/24720192/154626868-5eb9f7cc-7118-45bb-ad87-c66719bd959c.png)

- Run on `ubuntu`, `windows` and `macos`
  - Installed packages can be different according to OS
- `PASS` and `FAIL` is the result of self verification, not the result of github action running.
  - This is because we may need to merge the PR even there are some warnings or criticals.
- (Stretch) Find which package installs forbidden packages

### Related PR/Issue

- Draft : #288

### Todo

- [x] Add README.md #295
- [x] Add `license-checker` to `package.json` #335
- [x] Add blocklist for package and licenses #292
- [x] Add script for license verification #323 
- [x] Add script for generating comment with verification result #333
- [x] Add script for applying license verification to Github Action #342
- [x] Bug fix
  - [x] #347 
  - [x] #350

**Comment by llFreetimell** [comment]
### self-diagnosis before this issue is done

/cc @hyunsik-yoon 

```bash
$ cd ONE-vscode
ONE-vscode$ npm install license-checker
ONE-vscode$ npx license-checker
├─ @babel/code-frame@7.12.11
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/babel/babel
│  ├─ publisher: Sebastian McKenzie
│  ├─ email: sebmck@gmail.com
│  ├─ path: /home/seok/HDD/repos/ONE-vscode/node_modules/@babel/code-frame
│  └─ licenseFile: /home/seok/HDD/repos/ONE-vscode/node_modules/@babel/code-frame/LICENSE
├─ @babel/helper-validator-identifier@7.14.9
│  ├─ licenses: MIT
...
ONE-vscode$ npx license-checker --summary
├─ MIT: 207
├─ ISC: 43
├─ BSD-2-Clause: 11
├─ BSD-3-Clause: 9
├─ Apache-2.0: 8
├─ MIT*: 3
├─ Python-2.0: 1
├─ Unlicense: 1
├─ Custom: http://github.com/substack/node-bufferlist: 1
├─ Apache*: 1
├─ CC-BY-3.0: 1
├─ CC0-1.0: 1
├─ (MIT AND CC-BY-3.0): 1
├─ 0BSD: 1
└─ (MIT OR CC0-1.0): 1
```

**Comment by hyunsik-yoon** [comment]
`license-checker` has [yahoo license](https://github.com/davglass/license-checker/blob/master/LICENSE). Interesting. 😸

**Comment by llFreetimell** [comment]
Actually, copyright owner is Yahoo and License is BSD-3 Clause :D

**Comment by llFreetimell** [comment]
Finally Done!
