### ISSUE TITLE
Support to generate vsix package file

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#293]
## What

This issue aims to generate vsix package file.

## Todo

- [x] Add `repository` and `publisher` fields to package json (#294)
- [x] Build an extension package file (vsix file) *(Manually)*
- [x] Add test CI to generate vsix package file (#349)
- [ ] Verify the generated extension package

**Comment by jyoungyun** [comment]
## VSCE

"Visual Studio Code Extensions"
- A command line tool for packaging, publishing,, and managing VS Code extensions

### Pre-requirement
- Node.js
- vsce

### Usage
- Generate package file
   ```
   $ vsce package
   ```
- Login publisher using personal access token
   ```
   $ vsce login <publisher name>
   ```
- Publish package file
   - command line
   - manually upload it
   ```
   $ vsce publish
   ```

### Need to field in `package.json`
- publisher : The publisher name
- repository
   - type
   - url

### Need to consider
* Do not publish the user-provided SVG images
   - The icon in `package.json` may not be an SVG
   - The badges in `package.json` may not be SVGs unless trusted badge providers
   - Image URLs in `README.md` and `CHANGELOG.md` need to resolve to `https` URLs
   - Images in `README.md` and `CHANGELOG.md` may not be SVGs unless trusted badge providers
* Get a Personal Access Token
   - Create your own organizations in Azure DevOps
      - https://docs.microsoft.com/ko-kr/azure/devops/organizations/accounts/create-organization?view=azure-devops
* Version?
    - ONE version? or 1.0?

### Local test
You can install it manually.

**CLI**
```
code --install-extension one-vscode-0.0.1.vsix
```

or 

**VSCode**
1. Open VS Code
2. Open the "Extensions" sidebar ("Ctrl+Shift+X")
3. Click on the ellipsis icon in the top right corner of the Extensions sidebar menu
4. Select "Install from VSIX..."

refer to: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by jyoungyun** [comment]
(Information)

Support to generate multiple extension package in one git repo.
e.g. https://github.com/microsoft/vscode-cpptools.git

vscode-cpptools
   - Extension -> ms-vscode.cpptools
      - package.json 
   - ExtensionPack -> ms-vscode.cpptools-extension-pack
      - package.json
      - Install a set of popular extensions for C++ development (ms-vscode.cpptools, ms-vscode.cpptools-themes, etc.)
   - Themes -> ms-vscode.cpptools-themes
      - package.json

**Comment by jyoungyun** [comment]
The `vsce package` will ignore some files that described in the `.vscodeignore` file.

(Tip)
How to describe ignoring files:

1. Ignore all files and then add some files to install with `!` character.

```
* # ignore all files
!README.md # not ignore this file
```

2. By default, add all files and ignore unnecessary files

```
# ignore vscode settings for extension development
.vscode/**
# ignore node_modules
node_modules/**
```

**Comment by jyoungyun** [comment]
- [ ] Verify the generated extension package

This was not completed in this sprint period. I need a little more research on how to verify the generated extension package, and will be registered as an issue later.
