### ISSUE TITLE
[CI] Add copyright checker

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE-vscode#298]
### What?

Let's enable copyright checker in Github Action!

### Why?

Most of pull requests include new files which are not copied&pasted from other files.
It means that we may forget to insert copyright statement.
Let's reduce such mistake by copyright checker :)

### Todo

- [x] Add copyright statement to missing files
  - [x] #314
  - [x] #315
  - [x] #324
  - [x] #325
- [x] Create a script file to check copyright #321
- [x] Enable it in Github Action #329

#### Draft

- #302

**Comment by llFreetimell** [comment]
Done!

**Comment by llFreetimell** [comment]
### Bugfix Log

- #432
