### ISSUE TITLE
[UX] Install, Uninstall, Update & Initial Setting

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#306]
### Purpose

It aims to implement functions for a series of processes that install, update and remove an extension package of this project.

### A thing to do

- [x] Define ONE docker structure (#344)
- [x] Support to generate vsix package file (#293)
- [x] Remove ONE-vscode related files when uninstall
- [ ] Support auto update
- [ ] Support manual update
- [ ] Support and test multiple OS versions

### Purpose

It aims to configure the initial environment to operate this project.

### A thing to do

- [ ] Configure the currently available toolchain list from artifactory
- [ ] Configure of compiler installed on local pc (docker, debian)
- [ ] Configure of compiler list installed on remote pc (after setting remote ip address)
- [ ] Configure of executor list connected to local pc (sdb, simulator)
- [ ] Configure of executor list connected to remote pc (after setting remote ip address)
- [ ] Setup UI
    - [x] welcome UI ([what is welcome view?](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome) #330)
    - [x] model directory setting UI (#330)
    - [ ] compiler install UI
    - [ ] compiler uninstall UI
    - [ ] executor connection UI
    - [ ] executor disconnection UI

**Comment by hyunsik-yoon** [comment]
# Monthly Goal 

WIP

**Comment by YongseopKim** [comment]
I'm interested in impl below `Env`s (NOT UI)
- Compile/Execution
- Local/Remote(ssh)
- docker
- tizen
- tv(sdb)
