### ISSUE TITLE
[UX] Add Compiler View

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#430]
Let's add compiler view on ONE view.

The detail job to be performed for this sprint:
- [x] Add compiler toolchain view (#429)
- [x] Add refresh button to the right top of Compiler View (#446)
- [ ] Add local compiler toolchain (draft pr #390)
- [ ] Update compiler view list

**Comment by jyoungyun** [comment]
- [ ] Add local compiler toolchain (draft pr #390)
- [ ] Update compiler view list

We have changed how to provide backend extension to use a separated extension. So my draft PR did not fit the changed design. I will continue this job in the next sprint.
