### ISSUE TITLE
[UX] Add Compiler Toolset API

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#460]
Let's add compiler toolset API on ONE view.

- [x] Add Install button (#470)
- [x] Add quick input for installation (PR: #547, draft: #474)
- [x] Design compiler toolset api in consideration of one-vscode backend extension (#537, #546)
- [ ] Add local compiler toolchain (draft pr #390)
- [ ] Update compiler view list

Related issue: #455

**Comment by jyoungyun** [comment]
I couldn't complete this work during the [Sprint (Apr 11 to Apr 22)](https://github.com/Samsung/ONE-vscode/milestone/3). So I want to go to the next Spring([Sprint (Apr 25 to May 6)](https://github.com/Samsung/ONE-vscode/milestone/4)) and proceed.

**Comment by jyoungyun** [comment]
I will make another issue for updating toolchain view.
Other job was merged and done.
