### ISSUE TITLE
[UX] Update toolchain view

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE-vscode#569]
Let's try to finish the following within May. 😨 😅 🥵 🍺 

- [x] Enhanced "show installable toolchains"
  - [x] #573
    - [x] `toolchainTypes()` 
      - returns, e.g., `['official', 'nightly']`
    - [x] `toolchains()` -> `toolchains(toolchainType: string, from: number, count: number)` 
      - why? there could be, e.g., tons of versions in some toolchain type, e.g., `nightly`.
      - e.g., `toolchains('nightly', 10, 20)` returns 20 nightly versions starting from recent 10th version
    - [ ] remove deprecated code
  - [x] Frontend
     - [x] #684
  - [ ] unit test (if necessary)
    - [ ] backend impl
  - [x] #578
  - [x] Solve prerequisite to use a specific debian repo
    - e.g., registrer a specific debian repo, installing required packages, e.g., `ca-certificates`, `wget`, `gnupg2`, etc.
    - [x] #627
- [x] Show already-installed toolchain
  - [x] #659
  - [ ] function & view UI
     - [x] show list (draft: #657)
        - [x] #658 
     - [ ] show dependency information (draft: #688)
        - [x] #690
  - [ ] unit test (if necessary)
    - [ ] view UI
    - [x] backend impl
- [x] #577
   - [x] #589
   - [x] #634
   - [x] #636
- [x] Uninstall toolchain (draft: #699)
  - [x] check backend API 
     - [x] Add automatic yes and quiet option to uninstall command (PR 54)
  - [x] function & view UI
     - [x] #665 
     - [x] #707
  - [ ] unit test (if necessary)
    - [ ] view UI
- [x] #653
  - [x] check backend API
     - [x] Set install and uninstall to root (PR 45)
     - [x] Use aptitude tool when installing toolchain (PR 51)
  - [x] function & view UI
     - [x] #652
  - [ ] unit test (if necessary)
    - [ ] view UI

### Improvement point
- [ ] Revise backend API
   - [ ] `class Compiler` -> `class Toolchain`
- [ ] Toolchain view
   - [ ] Improve dependency information UI
- [ ] Toolchain API
   - [x] #704
- [ ] Install
   - [ ] frontend (one-vscode)
     - [ ] Improve UI
       - [x] #706
       - [ ] Improve progress UI
       - [ ] Encrypt user password
     - [ ] advanced functions
       - [ ] Install latest official toolchain (#779)
       - [ ] Install old official toolchain (#779)

**Comment by jyoungyun** [comment]
There are a few parts to consider.

Enhanced "show installable toolchains"
   * If the artifactory data is changed when user requests toolchain lists, how can we control this situation?

Show already-installed toolchain
   - backend impl (May not be needed?)
        * The current implementation asks if it is installed to all available lists. It takes a lot of resource to ask it. How about returning an information whether it is installed together when it first returns the list?

**Comment by hyunsik-yoon** [comment]
> If the artifactory data is changed when user requests toolchain lists, how can we control this situation?

Maybe we can have `setInterval()` that keeps calling `apt-get update` one or twice per day while ONE-vscode is up and running.
However, some users may not call `apt-get update` so we may need to find out some way to call `apt-get update` for backend Debian repo.


> - backend impl (May not be needed?)
>   - The current implementation asks if it is installed to all available lists. It takes a lot of resource to ask it. How about returning an information whether it is installed together when it first returns the list?

How about having the following API?

`Toolchain.getBackendInfo(backendVersion: string): backendInfo;`

ONE-vscode refreshes its toolchain list view when it is up for the first time. At that time, the UI can call the above function to get more specific info.

**Comment by jyoungyun** [comment]
> ONE-vscode refreshes its toolchain list view when it is up for the first time. At that time, the UI can call the above function to get more specific info.

How about adding `installed` variable to `ToolchainInfo` structure? Then we do not need to make an additional call for this job.

**Comment by jyoungyun** [comment]
## Toolchain View Scenario

### Initial loading
- No apt-source + No toolchain
   - Nothing to do
- No apt-source + installed toolchain
   - Show information message `Prerequisites has not been set yet. Do you want to set it up now?`
   - If yes, call prerequisites and then show installed toolchain in toolchain view
   - If no, no toolchain in toolchain view
   - When? User installed toolchain and then modify apt source lists
   - Problem? Failed to get toolchain information because there is no information about toolchain in apt-cache
- Registered apt-source + No toolchain
   - Nothing to do
- Registered apt-source + toolchain
   - Show installed toolchain in toolchain view automatically

**Comment by jyoungyun** [comment]
Almost features were merged. So I will close this issue at this point and I will continue the related job on another issue.
