### ISSUE TITLE
Implement the matching function between json and circle node

### ISSUE THREAD

**Issue by CODe1995** [Samsung/ONE-vscode#66]
## Pre-step
We finished analyzing the `circle file` structure and identifying the relationship between nodes using typescript. (#36, #46)
* Node relationship analysis was performed with reference to [netron](https://netron.app/).

## Current-step
We match the information of the `json file` generated from Backend to the corresponding node and implement the visualization function.
This function compares the `old json file` with the `new json file` and visualizes it. (Both json files refer to the same circle file)

## Current Progress
![circletracer_2](https://user-images.githubusercontent.com/47562093/135200733-83a19550-d7a5-4d6d-9b0a-0c2b7107ffc3.gif)

## Todo
- [x] Register the command to execute the function #183 
- [x] Read circle file with typescript
   - [x] Add a dependency to use flatbuffers #195 
   - [x] Compile Flatbuffers with typescript #199 
   - [x] Define the type of tensor #207 
   - [x] Analyze builtinOptions #213 
   - [x] Register tensor in subgraph in advance #217 
   - [x] Get the input data corresponding to each operator #209 
   - [x] Get the output data corresponding to each operator #211 
- [x] Analyze the circle file and process the data
- [x] Reads two json files and maps them to processed data
- [x] Visualize the processed data in the form of a node graph
- [x] Display duration next to each node graph

**Comment by llFreetimell** [comment]
@CODe1995

Could you add "What you want to do in this issue" at the main comment? :)
And what you are doing for achieving the goal can be written below main comments :D
(You do not need to fix it now, just FYI)

**Comment by llFreetimell** [comment]
You can use following materials to support this issue :)

- [sample2.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7096080/sample2.profile.json.txt)
- [sample3.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7105526/sample3.profile.json.txt)
- [sample.circle.zip](https://github.com/Samsung/ONE-vscode/files/7141331/sample.circle.zip)

**Comment by llFreetimell** [comment]
Please only check the checkbox when related PR is merged :)

**Comment by llFreetimell** [comment]
Please remove `.txt` from the file name.

[simple_add.circle.txt](https://github.com/Samsung/ONE-vscode/files/7282959/simple_add.circle.txt)
