### ISSUE TITLE
[OneExplorer] Candidate Features (June 2022)

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#695]
From #584 
For #712

### Key bindings
reference : [vscode web link](https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings)

- #729
- [ ] Add Rename Key binding : F2
- [ ] Add Refresh Key binding : ctrl R

### More commands
- [x] #731 Add open with TextEditor command 
- [x] #736 
- [x] #737 
- [x] #906
- [ ] Add open in explorer view command (workbench.files.action.showActiveFileInExplorer)
- [ ] Reorder commands in contexts

### Create Config - Better UI
from [this comment](https://github.sec.samsung.net/RS7-RuntimeNTools/secret/issues/187#issuecomment-1522094)
- [x] #745 Add input verify and value selection 
- [x] #747 Expand the base model node when a new cfg is created
- [x] #747 Open a new cfg in the editor at creation
- [ ] Select a new cfg in the editor at creation
  - [x] Use TreeView API
  - [ ] Implement reveal command
    - [ ] #908 (to map from OneNode to Uri)
    - [ ] Implement getParent api (required for reveal command)
- [ ] Show a full path 

> How about these features?
> 1. showing full path in the input box and select the file name part
> ![image](https://user-images.githubusercontent.com/50489513/171588950-ebe8482c-28a8-4687-b068-a9166b6b670b.png)
> or
> 2. showing faded path after the file name
> ![image](https://user-images.githubusercontent.com/50489513/171589197-b773f2a6-d8e9-4fed-9018-3e28481abe6d.png)
> 
> _Originally posted by @yunjayh in https://github.com/Samsung/ONE-vscode/pull/745#pullrequestreview-993198044_

 
### Automatic Cfg Edit
from [this comment](https://github.sec.samsung.net/RS7-RuntimeNTools/secret/issues/187#issuecomment-1522094)
- [ ] #768

### Prevent errors
- [ ] #881
- [ ] Prevent errors from virtualenv .cfg file

----

### Run
- Add ⏯️ icon for cfg run
  - [ ] #905 
- [ ]  Decide behavior when toolchain is not installed
> This icon is not available if the toolchain is not installed.
> https://github.com/Samsung/ONE-vscode/pull/905#issuecomment-1171863762

### Drag-and-Drop
- Drag-and-Drop inside OneExplorerView

### File copy
- copy

### File delete
- Delete cfg file
- Delete base model file
- Delete auto generated files

### User-friendly Features
- Notify users who don't have ANY config file.
From https://github.com/Samsung/ONE-vscode/pull/579#discussion_r869815440

> For those user who don't have idea about ONE config, we can provide vscode notification saying: You don't have any ONE configuration in your workspace. Try create one by clicking + next to your model files. [reference:notification](https://code.visualstudio.com/api/ux-guidelines/notifications)

- Provide a 'welcome view'
From https://github.com/Samsung/ONE-vscode/pull/579#discussion_r869815440

> We can provide more details on welcome view.
> [link: about welcome view](https://code.visualstudio.com/api/ux-guidelines/views#welcome-views)

### Advanced
- Auto-configure cfg on file creation
- ~~Auto-refresh on ActiveTextEditor change : reflect change even when the user doesn't hit ctrl-s while working on .cfg~~ (removed as it can make user confused)
- Drag-and-Drop across OneExplorerView and filesystem
- Copy cfg file to another base model

**Comment by dayo09** [comment]
Let's close this for now. Some unsupported features are considered to be low-priorities. Use this as a backlog.
