### ISSUE TITLE
[Jsontracer] Show profiling json file and bar-chart

### ISSUE THREAD

**Issue by parkjisu6239** [Samsung/ONE-vscode#94]
## What?
Let's show following profiling json file in vscode extension.

## Sample data
- [sample.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7175092/sample.profile.json.txt)
- [sample2.profile.json.txt](https://github.com/Samsung/ONE-vscode/files/7175093/sample2.profile.json.txt)

## Preview
![image](https://user-images.githubusercontent.com/42528189/133554365-e6389219-e880-48c9-9a88-3ca31902539f.png)

## Todo
- [x] Register this feature at Command list. #154
- [x] Click `Load`, a file selection dialog will pop up. #159 
- [x] Show timeline (with scroll bar) and bar-chart. #184 
- [x] Show pid`(GPU/CPU) utilization ratio. #170 
- [x] Open or close the panel. #170 
- [x] Make the color a bit prettier. #155
- [x] Zoom in / Zoom out #141 
  - [x] by button
  - [x] by scroll
- [x] Change The scale dynamically as you zoom in or out. #171 
- [x] You can click on the bar to see More info. #188 
  - [x] A single choice.
  - [x] A multi-selection
- [x] All elements follow the vscdoe theme color. #142 
- [ ] Show the node graph as a new web view, If you click `Origin`.
- [ ] Capture 
  - [ ] Capture complete message pop-up
  - [ ] Solve `the Rejected problem` from vcode webview due to security issues
- [x] If the scroll bar moves too fast, the scale will not be deleted or created normally. #141 

## How to run

1. `npm install`
2. `npm run build`
3. Press `F5` to run extension
4. When a new window in vscode opens, press `ctrl + shift + P` to enter `ONE: one-vscode-extension` command.

## Linked draft and Issue
- #93 
- #28 

## Need
It hasn't been PR yet, so if you want to use the demo version, please refer to the draft. :)
After using it, please write in the comments about `the feature you need` or `want to fix`.
We will develop it after reviewing it.

/cc @CODe1995 @yesfordev @parkjisu6239 @donggillee-dev @wnsdud4197
/thanks to @llFreetimell

**Comment by llFreetimell** [comment]
@parkjisu6239 

Could you change all the things in "Done" to "Todo" and add bullets?
Because we did only in draft, not official PR :D

**Comment by parkjisu6239** [comment]
@llFreetimell

Okay, I'll fix it!

**Comment by llFreetimell** [comment]
@parkjisu6239 

My intention was following :D

- Add an item with a checkbox
- Create a PR
- Attach the PRs' number at the end of bullet
- Merge the PRs
- After all related PRs are merged, click the checkbox!

**Comment by parkjisu6239** [comment]
@llFreetimell

I totally understood! I'll check the functions that merged PRs.

**Comment by llFreetimell** [comment]
So you can remove "Done" section :)
It's the last request!

**Comment by seanshpark** [comment]
Closing as not active. Feel free to reopen if needed.

**Comment by dayo09** [comment]
I tried the tool with an aid of @llFreetimell.
I am sharing this steps.

### How to run JsonTracer

1. Open `src/JsonTracer.ts` on vscode and push `F5 key`
2. A new vscode window will pop up
3. Open a command palatte with a shortcut `ctrl`+`shift`+`p`.
4. Type "ONE", then the available commands will show up.
